name: Tests

on:
  push:
    branches:
      - ci/setup-python-workaround

jobs:
  tests-deadsnakes:
    runs-on: ubuntu-18.04
    if: ${{ false }}
    name: Tests on Linux with Python 3.10 from deadsnakes
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.10 from repo
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt update
          sudo apt install python3.10 -y
          sudo ln -s -f /usr/bin/python3 python3.10
          python3.10 --version
          python3 --version
          python --version

      - name: Repros
        run: |
          curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
          export PATH="~/.local/bin:$PATH"

          ulimit -c unlimited
          python3.10 -m venv --without-pip .venv
          source .venv/bin/activate
          pip install --upgrade pip
          .venv/bin/python3 repro.py

  tests-toolcache-env:
    runs-on: ubuntu-18.04
    if: ${{ false }}
    name: Tests on Linux with Python 3.10 from toolcache with env
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Repros
        run: |
          ulimit -c unlimited
          python3.10 -m venv --without-pip .venv
          source .venv/bin/activate
          pip install --upgrade pip
          .venv/bin/python3 repro.py

  tests-toolcach:
    runs-on: ubuntu-18.04
    name: Tests on Linux with Python 3.10 from toolcache
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Repros
        run: |
          sudo apt-get update
          sudo apt-get install systemd-coredump strace
          ulimit -c unlimited
          python --version
          strace -Ff -tt python3 repro.py || true
          sleep 10
          set -x
          ls -la
          ls -la /var/lib/systemd/coredump
          ls -la /tmp
          coredumpctl list
          valgrind --track-origins=yes `which python`
          valgrind --track-origins=yes /usr/bin/strace
